# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82f6fc8634f3a0199c2fd81f68a44b6f32c5c1767cb3333ccbcd6470c61e9f65ff913ff62c56fe25459817f00b3b2fc97e837b3eecb112d2a2b36b2d84990344

test:
  secret_key_base: d9944ebcc1942bf50950671392f6b41547cc01bc1ed143a430be21fa9a66fb31d9b331fa51dd60b903dbb09c55bd03b9bff1bb9ff721c96d87c5d79aa213500e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
